### ISSUE TITLE
Is not compatibility with latest version of Verdaccio

### ISSUE THREAD

**Issue by XuJinNet** [deeplay-io/verdaccio-openid-connect#18]
Hello, the current latest stable version of Verdaccio is 5.21.1, after installing this plugin, running the service fails.

```
verdaccio  | warn --- config file  - /verdaccio/conf/config.yaml 
verdaccio  | error--- error loading a plugin openid-connect: {} 
verdaccio  | error--- verdaccio-openid-connect doesn't look like a valid plugin 
verdaccio  | fatal--- uncaught exception, please report this
verdaccio  | Error: sanity check has failed, "openid-connect" is not a valid plugin
verdaccio  |     at /usr/local/lib/node_modules/verdaccio/build/lib/plugin-loader.js:164:13
verdaccio  |     at Array.map (<anonymous>)
verdaccio  |     at loadPlugin (/usr/local/lib/node_modules/verdaccio/build/lib/plugin-loader.js:61:37)
verdaccio  |     at Auth._loadPlugin (/usr/local/lib/node_modules/verdaccio/build/lib/auth.js:40:38)
verdaccio  |     at new Auth (/usr/local/lib/node_modules/verdaccio/build/lib/auth.js:32:25)
verdaccio  |     at defineAPI (/usr/local/lib/node_modules/verdaccio/build/api/index.js:35:16)
verdaccio  |     at _default (/usr/local/lib/node_modules/verdaccio/build/api/index.js:112:10)
verdaccio  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
verdaccio exited with code 255
```

**Comment by XuJinNet** [comment]
Sorry, my configuration is incomplete.
This issue can be closed.

**Comment by PeterSR** [comment]
I am getting the same with version 5.31.1 of Verdaccio and 2.0.0 of this package (latest at the time of writing).

What did you do?

**Comment by cudatuda** [comment]
@PeterSR  Just found the cause!
Take a look at `clientSecret` property in the config file - its value should not contain single quotes (like in example config). So i just pasted client secret without quotes and issue disappeared: `clientSecret: '...'` -> `clientSecret: ...`. I hope this will help!

**Comment by PeterSR** [comment]
I am using a helm chart for Verdaccio with the following configmap that embeds the `config.yaml` into the deployment:

```yaml
apiVersion: v1
data:
  config.yaml: |-
    ...

    auth:
      ...
      openid-connect:
        issuer: https://accounts.google.com
        clientId: 39....apps.googleusercontent.com
        clientSecret: GOC....HBD
        scope: openid profile email
```

And I don't have any quotes around the value of `clientSecret`.
